### ISSUE TITLE
Ores doesn't spawn at all.

### ISSUE THREAD

**Issue by Bazyliii** [Luligabi1/DenseOresRefabricated#5]
Like in the title, ores are shown in Jei but aren't generated.

Game version 1.17.1 Java 17
Newest Fabric and Fabric API
No mods except Jei, Fabric API and Dense Ores 1.1

I hope we can somehow fix it.

**Comment by Luligabi1** [comment]
Couldn't reproduce - Ores are generating normally. Be aware they are quite rare and make sure to check new chunks, as chunks generated before the mod was installed will not contain them.

**Comment by Bazyliii** [comment]
Oh yeah, you are right. They are so rare that i thought that they are not really here.

Sorry for false alarm.
